### ISSUE TITLE
Error: Cannot find module '@vue/cli-plugin-router'

### ISSUE THREAD

**Issue by snickers2k** [alfg/ffmpeg-commander#23]
```
snikay@cloudBox:/opt/ffmpeg-commander$ npm run serve

> ffmpeg-commander@0.7.2 serve
> vue-cli-service serve

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@vue/cli-plugin-router'
Require stack:
- /opt/ffmpeg-commander/node_modules/@vue/cli-service/lib/Service.js
- /opt/ffmpeg-commander/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at idToPlugin (/opt/ffmpeg-commander/node_modules/@vue/cli-service/lib/Service.js:150:14)
    at /opt/ffmpeg-commander/node_modules/@vue/cli-service/lib/Service.js:190:20
    at Array.map (<anonymous>)
    at Service.resolvePlugins (/opt/ffmpeg-commander/node_modules/@vue/cli-service/lib/Service.js:176:10)
    at new Service (/opt/ffmpeg-commander/node_modules/@vue/cli-service/lib/Service.js:34:25)
    at Object.<anonymous> (/opt/ffmpeg-commander/node_modules/@vue/cli-service/bin/vue-cli-service.js:16:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/ffmpeg-commander/node_modules/@vue/cli-service/lib/Service.js',
    '/opt/ffmpeg-commander/node_modules/@vue/cli-service/bin/vue-cli-service.js'
  ]
}

Node.js v17.2.0
```

is it my bad or should it be updated ? :) 

thanks

**Comment by alfg** [comment]
Hi @snickers2k, can you try on either LTS release v14 or v16?

**Comment by alfg** [comment]
Closing. I updated the readme with the support versions of Node.
